### ISSUE TITLE
Dynamic import does not work on windows after 2.0.7 (re-open)

### ISSUE THREAD

**Issue by jackysee** [webpack-contrib/karma-webpack#317] opened 2018-03-15 08:01 UTC
**This is an re-open issue of #291. I upgraded the karma and karma webpack, but the dynamic import still not work.**

**Webpack version:**
3.10.0

**Webpack Karma version**:
2.0.13

**Karma version**:
2.0.0

**Please tell us about your environment:**
Windows 10

**Browser:** Chrome

**Current behavior:**
Having the webpack do the code splitting at dynamic import statement e.g. `import('./file.js')`, karma serve the path as system file path and chrome report that it cannot load the resource:
```
Not allowed to load local resource: file:///C:/Users/jackysee/AppData/Local/Temp/_karma_webpack_/0.bundle.js
```

**Expected/desired behavior:**
It should  load the resource at e.g. `http://localhost:9867/_karma_webpack/0.bundle.js`, just as it did in version karma-webpack 2.0.6.

* **demo**

https://github.com/jackysee/karam-webpack-test2

**Comment by philipahlberg** [comment] 2018-03-15 12:47
Possible duplicate of #316 (webpack 3 vs webpack 4)

**Comment by liqueurdetoile** [comment] 2018-03-21 20:11
I confirm there's still an issue with any version > 2.0.6 of karma-webpack on Windows to load dynamic imports due to this commit : https://github.com/webpack-contrib/karma-webpack/commit/0616dda

On Windows, os.tmpdir() returns an absolute file path that is not allowed to be loaded through ajax.

**Comment by Klathmon** [comment] 2018-04-18 19:09
Yeah i'm still getting the same issue, and I can confirm that going back to 2.0.6 solves the problem temporarily.

**Comment by pierluca** [comment] 2018-06-27 06:40
I have the same issue. Same environment as above (Windows 10, Karma-webpack 3+) and I can confirm it works with 2.0.6 (thanks for the workaround by the way)

**Comment by michael-ciniawsky** [comment] 2018-09-07 19:57
#338

**Closed by michael-ciniawsky** 2018-09-07 19:57 UTC

**Comment by johnnyreilly** [comment] 2018-09-24 07:12
I've just tested 4.0.0-rc.2 on Windows; still a problem I'm afraid. It's what we use in [ts-loader](https://github.com/TypeStrong/ts-loader) for our execution test pack. 

You can see this PR upgrades from 2.0.6 to 4.0.0-rc2 and then experiences issues:

https://github.com/TypeStrong/ts-loader/pull/840

Linux is fine; Windows is not. The failing tests all relate to code splitting / dynamic imports.

I'll open a new issue to track this and link back.
