### ISSUE TITLE
karma-webpack@3.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by EvalGitHub** [webpack-contrib/karma-webpack#406] opened 2019-06-07 10:34 UTC

**Comment by ryanclark** [comment] 2019-06-07 10:35
Sorry, its not clear what the issue is here?

**Comment by EvalGitHub** [comment] 2019-06-07 10:40
"npm install --save-dev webpack karma karma-webpack" in my project , i get this info shown above

**Comment by ryanclark** [comment] 2019-06-07 10:44
The version of `karma-webpack` you need for webpack v4 is published under the tags `@next` or `@dev`. The current `@latest` supports v3 only. Try `npm install karma-webpack@next`.

**Comment by evilebottnawi** [comment] 2019-06-07 10:50
@ryanclark Maybe time to release `@next`? Also drop node@6?

**Comment by ryanclark** [comment] 2019-06-07 10:51
@evilebottnawi good shout, I'll sort this out over the weekend

**Comment by ryanclark** [comment] 2019-06-07 10:55
I've made an issue to address this, closing this now.

**Closed by ryanclark** 2019-06-07 10:55 UTC
